(self.AMP=self.AMP||[]).push({n:"amp-auto-ads",v:"2005151844001",f:(function(AMP,_){
var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var k;a:{var ba={a:!0},l={};try{l.__proto__=ba;k=l.a;break a}catch(a){}k=!1}g=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=g,ca=Object.prototype.toString;function t(a){return a||{}};function u(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function v(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var w=self.AMP_CONFIG||{},da=("string"==typeof w.cdnProxyRegex?new RegExp(w.cdnProxyRegex):w.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function x(a){if(self.document&&self.document.head&&(!self.location||!da.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}w.cdnUrl||x("runtime-host");w.geoApiUrl||x("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var y=self.__AMP_LOG;function z(){if(!y.user)throw Error("failed to call initLogConstructor");return y.user}function A(a,b){z().assert(a,b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};var ea={type:!0,"rtc-config":!0};function B(a,b){if(!a[b])return{};if("[object Object]"!==ca.call(a[b])||Array.isArray(a[b]))return z().warn("amp-auto-ads",b+" property not an object"),{};b=a[b];var c={},d;for(d in b)if(ea[d]||v(d,"data-")){var e=typeof b[d];"number"!=e&&"string"!=e&&"boolean"!=e?z().warn("amp-auto-ads","Attribute type not supported: "+e):c[d]=String(b[d])}else z().warn("amp-auto-ads","Attribute not whitlisted: "+d);return c};function fa(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ha(a){return new Promise(function(b){b(a())})};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var C;function E(a,b,c){a=a.createElement(b);for(var d in c)a.setAttribute(d,c[d]);return a}function ia(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function ja(a,b){return a.closest?a.closest(b):ia(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}
function ka(a,b){if(void 0!==C)var c=C;else{try{var d=a.ownerDocument,e=d.createElement("div"),h=d.createElement("div");e.appendChild(h);c=e.querySelector(":scope div")===h}catch(p){c=!1}c=C=c}c?a=a.querySelectorAll(b.replace(/^|,/g,"$&:scope ")):(a.classList.add("i-amphtml-scoped"),b=b.replace(/^|,/g,"$&.i-amphtml-scoped "),b=a.querySelectorAll(b),a.classList.remove("i-amphtml-scoped"),a=b);return a}
function F(a){v(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new fa;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function G(){this.M=100;this.B=this.D=0;this.A=Object.create(null)}G.prototype.has=function(a){return!!this.A[a]};G.prototype.get=function(a){var b=this.A[a];if(b)return b.access=++this.B,b.payload};
G.prototype.put=function(a,b){this.has(a)||this.D++;this.A[a]={payload:b,access:this.B};if(!(this.D<=this.M)){if(y.dev)a=y.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.A;var c=this.B+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var h=d}}void 0!==h&&(delete a[h],this.D--)}};t({c:!0,v:!0,a:!0,ad:!0,action:!0});var H,I;
function J(a){H||(H=self.document.createElement("a"),I=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new G));var b=I,c=H;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a};function K(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return L(a,b)}function M(a,b){var c=N(a);c=N(c);c=c.isSingleDoc()?c.win:c;return L(c,b)}function N(a){return a.nodeType?K((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function L(a,b){var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};function O(a){return M(a,"documentInfo").get()}function P(a){return M(a,"viewport")};function Q(a){var b=M(a,"resources").getResourceForElementOptional(a);return b?b.getPageLayoutBoxAsync():K(a.ownerDocument.defaultView,"vsync").measurePromise(function(){return P(a).getLayoutRect(a)})};var la=["AMP-SIDEBAR","AMP-APP-BANNER"],ma={1:function(a,b){a.parentNode.insertBefore(b,a)},4:function(a,b){a.parentNode.insertBefore(b,a.nextSibling)},2:function(a,b){a.insertBefore(b,a.firstChild)},3:function(a,b){a.appendChild(b)}};function R(a,b,c,d,e,h){this.ampdoc=a;this.U=M(b,"mutator");this.H=b;this.V=c;this.P=d;this.I=e;this.S=h;this.F=null;this.l=0}R.prototype.getAdElement=function(){return this.F};
R.prototype.getEstimatedPosition=function(){var a=this;return Q(this.H).then(function(b){a:switch(a.V){case 1:case 2:b=b.top;break a;case 3:case 4:b=b.bottom;break a;default:throw Error("Unknown position");}return b})};
R.prototype.placeAd=function(a,b,c,d){var e=this;return this.getEstimatedPosition().then(function(h){return c.isTooNearAnAd(h).then(function(c){if(c)return e.l=3,e.l;e.F=d?na(e,a):oa(e,a,b.width);e.P(e.H,e.getAdElement());return d?F(e.getAdElement()).then(function(){return e.getAdElement().whenBuilt()}).then(function(){var a=!e.getAdElement().classList.contains("i-amphtml-layout-awaiting-size");e.l=a?2:1;return e.l}):Promise.resolve({height:b.height||250,margins:e.S}).then(function(a){return F(e.getAdElement()).then(function(){return e.getAdElement().whenBuilt()}).then(function(){return e.U.requestChangeSize(e.getAdElement(),
a.height,a.width,a.margins)}).then(function(){e.l=2;return e.l},function(){e.l=1;return e.l})})})})};function oa(a,b,c){b=Object.assign(t({layout:c?"fixed":"fixed-height",height:"0",width:c?c:"auto","class":"i-amphtml-layout-awaiting-size"}),b,a.I);return E(a.ampdoc.win.document,"amp-ad",b)}
function na(a,b){b=Object.assign(t({width:"100vw",height:"0",layout:"fixed","class":"i-amphtml-layout-awaiting-size","data-auto-format":"rspv","data-full-width":""}),b,a.I);return E(a.ampdoc.win.document,"amp-ad",b)}function pa(a,b){var c=b.placements;if(!c)return z().info("amp-auto-ads","No placements in config"),[];var d=[];c.forEach(function(b){qa(a,b,d)});return d}
function qa(a,b,c){var d=ma[b.pos];if(d){var e=b.anchor;if(e){var h=S(a.getRootNode(),e);if(h.length){var p=void 0;if(b.style){var m=parseInt(b.style.top_m,10),n=parseInt(b.style.bot_m,10);if(m||n)p={top:m||void 0,bottom:n||void 0}}h.forEach(function(e){if(ra(e,b.pos)){var h=B(b,"attributes");c.push(new R(a,e,b.pos,d,h,p))}})}else z().warn("amp-auto-ads","No anchor element found")}else z().warn("amp-auto-ads","No anchor in placement")}else z().warn("amp-auto-ads","No injector for position")}
function S(a,b){var c=b.selector;if(!c)return z().warn("amp-auto-ads","No selector in anchor"),[];c=[].slice.call(ka(a.documentElement||a,c));var d=b.min_c||0;0<d&&(c=c.filter(function(a){return a.textContent.length>=d}));"number"!=typeof b.index&&b.all||(c=(c=c[b.index||0])?[c]:[]);if(0==c.length)return[];if(b.sub){var e=[];c.forEach(function(a){e=e.concat(S(a,b.sub))});return e}return c}
function ra(a,b){var c=1==b||4==b?a.parentElement:a;return c?!la.some(function(a){return ja(c,a)?(z().warn("amp-auto-ads","Placement inside blacklisted ancestor: "+a),!0):!1}):(z().warn("amp-auto-ads","Parentless anchor with BEFORE/AFTER position."),!1)};function T(a,b){for(var c=[],d=4096-a.length,e=Object.keys(b),h=0;h<e.length;h++){var p=e[h],m=b[p];if(null!=m&&""!==m){var n=encodeURIComponent(p)+"=",q=encodeURIComponent(String(m)),D=n.length+q.length+1;if(D>d){var Y=q.substr(0,d-n.length-1).replace(/%\w?$/,"");Y&&c.push(n+Y);break}c.push(n+q);d-=D}}return c.length?a+"?"+c.join("&"):a};function U(a){this.j=a}f=U.prototype;f.isEnabled=function(){return!0};f.isResponsiveEnabled=function(){return!0};f.getConfigUrl=function(){var a=O(this.j),b=J(a.canonicalUrl).hostname,c=this.j.ownerDocument.defaultView;return T("//pagead2.googlesyndication.com/getconfig/ama",{client:this.j.getAttribute("data-ad-client"),plah:b,ama_t:"amp",url:a.canonicalUrl,debug_experiment_id:(/(?:#|,)deid=([\d,]+)/i.exec(c.location.hash)||[])[1]||null})};
f.getAttributes=function(){var a=t({type:"adsense","data-ad-client":this.j.getAttribute("data-ad-client")}),b=this.j.getAttribute("data-ad-host"),c=this.j.getAttribute("data-ad-host-channel");b&&(a["data-ad-host"]=b,c&&(a["data-ad-host-channel"]=c));return a};f.getDefaultAdConstraints=function(){var a=P(this.j).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};f.getSizing=function(){return{}};function sa(a){this.j=a}f=sa.prototype;f.isEnabled=function(){return!0};f.isResponsiveEnabled=function(){return!1};f.getConfigUrl=function(){var a=O(this.j),b=this.j.getAttribute("data-publisher-id"),c=this.j.getAttribute("data-tag-id");return T("//v2.denakop.com/ad-request/amp",{p:b,t:c,u:a.canonicalUrl,w:window.screen.width,h:window.screen.height})};f.getAttributes=function(){return t({layout:"fixed","data-multi-size-validation":"false",type:"doubleclick","data-ad":"denakop"})};
f.getDefaultAdConstraints=function(){var a=P(this.j).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};f.getSizing=function(){return{}};function ta(a){this.j=a}f=ta.prototype;f.isEnabled=function(){return!0};f.isResponsiveEnabled=function(){return!1};f.getConfigUrl=function(){var a=O(this.j),b=J(a.canonicalUrl).hostname;return T("//pagead2.googlesyndication.com/getconfig/ama",{client:this.j.getAttribute("data-ad-legacy-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};f.getAttributes=function(){return t({type:"doubleclick","data-slot":this.j.getAttribute("data-slot"),json:this.j.getAttribute("data-json")})};
f.getDefaultAdConstraints=function(){var a=P(this.j).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};f.getSizing=function(){var a=this.j.getAttribute("data-experiment");try{var b=JSON.parse(a)}catch(d){b=null}var c=b;return c?{height:c.height?Number(c.height):250,width:c.width?Number(c.width):void 0}:{}};function ua(a,b){return"adsense"==a?new U(b):"denakop"==a?new sa(b):"doubleclick"==a?new ta(b):null};function va(a,b,c,d,e){e=void 0===e?!1:e;this.L=a.slice(0);this.C=b;this.W=c;this.m=d;this.G=0;this.R=e}va.prototype.run=function(){var a=this;return this.m.isMaxAdCountReached()?ha(function(){return wa(a)}):xa(this).then(function(b){return b?a.run():wa(a)})};function wa(a){return{adsPlaced:a.G,totalAdsOnPage:a.m.getAdCount()}}
function xa(a){var b=a.L.shift();return b?b.placeAd(a.C,a.W,a.m,a.R).then(function(c){return 2==c?(a.m.addAd(b.getAdElement()),a.G++,!0):xa(a)}):(z().info("amp-auto-ads","unable to fulfill ad strategy"),Promise.resolve(!1))};function V(a,b){this.o=a;this.O=b.initialMinSpacing;this.K=b.subsequentMinSpacing.slice(0).sort(function(a,b){return a.adCount-b.adCount});this.T=b.maxAdCount;this.J=ya(this)}V.prototype.addAd=function(a){this.o.push(a);this.J=ya(this)};V.prototype.getAdCount=function(){return this.o.length};V.prototype.isMaxAdCountReached=function(){return this.getAdCount()>=this.T};V.prototype.isTooNearAnAd=function(a){return za(this,a,0)};
function za(a,b,c){return c>=a.o.length?Promise.resolve(!1):Aa(b,a.o[c]).then(function(d){return d<a.J?!0:za(a,b,c+1)})}function Aa(a,b){return Q(b).then(function(b){return a>=b.top&&a<=b.bottom?0:Math.min(Math.abs(a-b.top),Math.abs(a-b.bottom))})}function ya(a){for(var b=a.getAdCount(),c=a.O,d=0;d<a.K.length;d++){var e=a.K[d];e.adCount<=b&&(c=e.spacing)}return c}
function Ba(a){return[].slice.call(a.getRootNode().querySelectorAll("AMP-AD")).filter(function(a){return a.parentElement&&"AMP-STICKY-AD"==a.parentElement.tagName?!1:!0})}
function Ca(a,b){b=b.adConstraints;if(!b)return null;var c=P(a).getHeight(),d=Da(b.initialMinSpacing,c);if(null==d)return z().warn("amp-auto-ads","Invalid initial min spacing"),null;var e=(b.subsequentMinSpacing||[]).map(function(a){var b=a.adCount;if(null==b)return z().warn("amp-auto-ads","No subsequentMinSpacing adCount specified"),null;a=Da(a.spacing,c);return null==a?(z().warn("amp-auto-ads","Invalid subsequent min spacing"),null):{adCount:b,spacing:a}});return-1!=e.indexOf(null)?null:null==b.maxAdCount?
(z().warn("amp-auto-ads","No maxAdCount specified"),null):{initialMinSpacing:d,subsequentMinSpacing:e,maxAdCount:b.maxAdCount}}function Da(a,b){if(!a)return null;var c=parseFloat(a);return isNaN(c)||0>c?null:u(a,"px")?c:u(a,"vp")?c*b:null};function Ea(a,b,c){this.ampdoc=a;this.C=b;this.N=c}
Ea.prototype.run=function(){if(this.ampdoc.getRootNode().querySelector("AMP-STICKY-AD"))return z().warn("amp-auto-ads","Auto ads may not work because of already existing <amp-sticky-ad>."),Promise.resolve(!1);if(!z().assertArray(this.N.optInStatus||[]).includes(2))return Promise.resolve(!1);K(this.ampdoc.win,"extensions").installExtensionForDoc(this.ampdoc,"amp-sticky-ad","1.0");var a=P(this.ampdoc).getWidth(),b=Object.assign({},this.C,t({width:String(a),height:"100"}));a=this.ampdoc.win.document;
b=E(a,"amp-ad",b);a=E(a,"amp-sticky-ad",t({layout:"nodisplay"}));a.appendChild(b);b=this.ampdoc.getBody();b.insertBefore(a,b.firstChild);return Promise.resolve(!0)};function W(){return AMP.BaseElement.apply(this,arguments)||this}var X=AMP.BaseElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;if(r)r(W,X);else for(var Z in X)if("prototype"!=Z)if(Object.defineProperties){var Fa=Object.getOwnPropertyDescriptor(X,Z);Fa&&Object.defineProperty(W,Z,Fa)}else W[Z]=X[Z];W.X=X.prototype;
W.prototype.buildCallback=function(){var a=this,b=this.element.getAttribute("type");A(b,"Missing type attribute");var c=ua(b,this.element);A(c,"No AdNetworkConfig for type: "+b);if(c.isEnabled(this.win)){var d=this.getAmpDoc();K(this.win,"extensions").installExtensionForDoc(d,"amp-ad");this.getAmpDoc().whenFirstVisible().then(function(){return Ga(a,c.getConfigUrl())}).then(function(b){if(b){var e=b.noConfigReason;e&&a.user().warn("amp-auto-ads",e);var p=pa(d,b),m=Object.assign(t({}),c.getAttributes(),
B(b,"attributes")),n=c.getSizing(),q=Ca(d,b)||c.getDefaultAdConstraints();q=new V(Ba(d),q);(new va(p,m,n,q,c.isResponsiveEnabled())).run();var D=Object.assign(t({}),m,B(b,"stickyAdAttributes"));(new Ea(d,D,b)).run()}})}};W.prototype.isLayoutSupported=function(){return!0};
function Ga(a,b){return K(a.win,"xhr").fetchJson(b,{mode:"cors",method:"GET",credentials:"omit"}).then(function(a){return a.json()}).catch(function(b){a.user().error("amp-auto-ads","amp-auto-ads config xhr failed: "+b);return null})}(function(a){a.registerElement("amp-auto-ads",W)})(self.AMP);
})});

//# sourceMappingURL=amp-auto-ads-0.1.js.map
